In [1]:
import os
os.chdir(r'C:\Users\rajja\Documents\Synent Project\Task1_Titanic')

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Titanic.csv")

In [4]:
df.shape  #To see how many rows-columns are there

(891, 12)

In [5]:
df.head()  #First 5-rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.info()  # To see which coulmns are there and what's the data type and check how many null values are there

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.describe()  # For Statistical summary Like..

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.isnull().sum() #To check how many null values are there and where

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df['Age'].fillna(df['Age'].mean(), inplace=True) #To fill all null values in age  with mean of age

C:\Users\rajja\AppData\Local\Temp\ipykernel_17336\469113164.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True) #To fill all null values in age  with mean of age

In [10]:
df['Embarked'].fillna(df['Embarked'].mode, inplace=True) # To fill all null values in embarked with most comman values in embarked

In [11]:
df.drop(columns =['Cabin'] , inplace =True) # Drop the cabin column because more than 70% null values in cabin column

In [12]:
df.isnull().sum() #After fill and drop here is clean data with 0 null values

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [13]:
df.duplicated().sum() # Check how many duplicate value in dataset

np.int64(0)

In [14]:
df.drop_duplicates(inplace=True) #Drop all duplicate values in dataset

In [15]:
df.duplicated().sum()  #After drop a duplicate here is a 0 duplicate value

np.int64(0)

In [16]:
df['Survived']= df['Survived'].astype('bool')
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')

In [17]:
df.dtypes #After change the data type here is all correct data types

PassengerId       int64
Survived           bool
Pclass         category
Name             object
Sex            category
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Embarked       category
dtype: object

In [18]:
df.rename(columns={
    'PassengerId' : 'Passenger_Id',
    'Pclass' : 'Passenger_class',
    'SibSp' : 'Siblings_Spouses',
    'Parch' : 'Parents_Children',
    'Embarked': 'Port_of_Embarkation'
}, inplace=True)  # Change the columns name for better understanding

In [19]:
df.columns.tolist() # After change the colummns name here is the correct columns name

['Passenger_Id',
 'Survived',
 'Passenger_class',
 'Name',
 'Sex',
 'Age',
 'Siblings_Spouses',
 'Parents_Children',
 'Ticket',
 'Fare',
 'Port_of_Embarkation']

In [20]:
df.shape # Check  after all operation how many rows and columns are there

(891, 11)

In [21]:
df.head(10) # First 10 rows after clean the data

,Passenger_Id,Survived,Passenger_class,Name,Sex,Age,Siblings_Spouses,Parents_Children,Ticket,Fare,Port_of_Embarkation
0,1,False,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,True,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,False,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
5,6,False,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,Q
6,7,False,1,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,S
7,8,False,3,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,S
8,9,True,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,S
9,10,True,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,C

In [22]:
df.to_csv('Titanic_cleaned.csv' , index=False) # Save the clean data to a new file with no extra index